# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM audit

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
#      - name: Run NPM audit
#        run: npm audit fix
      - name: Raise PR
        run: |
          echo "---- Raising PR -----"
          touch text.txt
          echo "test" > text.txt
          git add .
          branchId=$(date +%Y%m%d%H%M%S)
          git status
          git checkout -b npm_audit_fix_$branchId
          echo "---- Creating branch -----"
          git branch
          echo "---- Creating PR -----"
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pulls \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "head": "head",
              "base": "base",
              "title": "NPM Audit Fix: $branchId",
              "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
              }' \
            --fail



